# Generated by Django 5.0.3 on 2024-03-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bolg',
            new_name='Blog',
        ),
    ]
